Submit Custom html card code in github
googledatastudio/experimental-visualizations pull request #67
Opened 2020-02-03 23:21 UTC by praveena-pappu

2020-02-12 23:02 UTC, musiciancodes requested changes

2020-02-12 23:02 UTC, y3l2n commented on viz/CustomHTMLCard/src/manifest.json
> +  "privacyPolicyUrl": "https://policies.google.com/privacy",
I don't think you can use the Google privacy policy and ToS. Delete these for now, I'll check on what should be used.

2020-02-12 23:02 UTC, y3l2n commented on viz/CustomHTMLCard/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
There shouldn't be both yarn.lock and package.lock - if you're using npm, keep package.lock if you're using yarn, use yarn.lock

2020-02-13 00:17 UTC, musiciancodes requested changes

2020-02-13 00:17 UTC, y3l2n commented on viz/CustomHTMLCard/README.md
> +Data Studio [community visualizations][community viz] allow you to write custom
Community Visualizations is usually capitalized. Markdown links need a link to work properly. Look up reference links here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

2020-02-13 00:17 UTC, y3l2n commented on viz/CustomHTMLCard/README.md
> +styling in the "Style" tab. User can mention the styling for the HTML body and row using the tags and class names. The classname for the row data is ".row". Sample styling looks like: "body{backgroun
The sample styling belongs in a "code block"

Should also link to the sample report here and maybe have screenshots of how/where to configure it

2020-02-13 00:17 UTC, y3l2n commented on viz/CustomHTMLCard/src/index.js
> +        for (var k in dimensionData) {
const k

2020-02-13 00:17 UTC, y3l2n commented on viz/CustomHTMLCard/src/index.js
> +          let fieldElement =
Any reason why this can't be a const?

2020-02-13 00:17 UTC, y3l2n commented on viz/CustomHTMLCard/src/index.js
> +        var rowDiv = $("<div class='row'>");
should either be let or const

2020-02-13 00:17 UTC, y3l2n commented on viz/CustomHTMLCard/src/index.js
> +    if (style != undefined && style != '') {
use !== here

2020-02-13 00:17 UTC, y3l2n commented on viz/CustomHTMLCard/src/manifest.json
> +  "packageUrl": "https://datastudio.google.com/open/1QhuGDiHKUQ-yBs4nfAOesdhr9RBeQPvm",
The report should look a little more polished - more whitespace, less crowded. Take a look at the gallery reports

2020-02-13 00:17 UTC, y3l2n commented on viz/CustomHTMLCard/src/manifest.json
> +  "organization": "Data Studio",
Organization should be "Data Studio Developer Relations"

2020-02-13 00:17 UTC, y3l2n commented on viz/CustomHTMLCard/src/manifest.json
> +  "description": "Community Viz lets users design and render their own viz in Data Studio. Using this card generator Community Viz we will let users render individual cards for each of their data row
Description should be shorter: closer to 10-15 words max

2020-02-18 21:57 UTC, praveena-pappu commented on viz/CustomHTMLCard/.project
> +<?xml version="1.0" encoding="UTF-8"?>
removed the file

2020-02-18 21:57 UTC, praveena-pappu commented on viz/CustomHTMLCard/.settings/org.eclipse.wst.jsdt.ui.superType.container
> +org.eclipse.wst.jsdt.launching.JRE_CONTAINER
removed the file

2020-02-18 21:58 UTC, praveena-pappu commented on viz/CustomHTMLCard/README.md
> +# Data Studio Community Visualization Local Development Template
Updated readme

2020-02-18 21:58 UTC, praveena-pappu commented on viz/CustomHTMLCard/src/localMessage.js
> +/**
removed the file

2020-02-18 21:58 UTC, praveena-pappu commented on viz/CustomHTMLCard/src/index.js
> +  var nameData = data.fields.chartDimension;
updated the var to let

2020-02-18 21:58 UTC, praveena-pappu commented on viz/CustomHTMLCard/src/manifest.json
> +  "privacyPolicyUrl": "https://policies.google.com/privacy",
removed PP and TOS links

2020-02-18 21:59 UTC, praveena-pappu commented on viz/CustomHTMLCard/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
removed yan.lock

2020-02-18 21:59 UTC, praveena-pappu commented on viz/CustomHTMLCard/README.md
> +styling in the "Style" tab. User can mention the styling for the HTML body and row using the tags and class names. The classname for the row data is ".row". Sample styling looks like: "body{backgroun
removed the code block and updated the link from Viz report

2020-02-18 21:59 UTC, praveena-pappu commented on viz/CustomHTMLCard/src/index.js
> +        for (var k in dimensionData) {
updated

2020-02-18 22:00 UTC, praveena-pappu commented on viz/CustomHTMLCard/src/index.js
> +          let fieldElement =
updated to const

2020-02-18 22:00 UTC, praveena-pappu commented on viz/CustomHTMLCard/src/index.js
> +        var rowDiv = $("<div class='row'>");
updated to const

2020-02-18 22:00 UTC, praveena-pappu commented on viz/CustomHTMLCard/src/index.js
> +    if (style != undefined && style != '') {
updated as per review comment

2020-02-18 22:00 UTC, praveena-pappu commented on viz/CustomHTMLCard/src/manifest.json
> +  "organization": "Data Studio",
Updated

2020-02-18 22:01 UTC, praveena-pappu commented on viz/CustomHTMLCard/src/manifest.json
> +  "description": "Community Viz lets users design and render their own viz in Data Studio. Using this card generator Community Viz we will let users render individual cards for each of their data row
changed the description

2020-02-18 22:07 UTC, musiciancodes requested changes

2020-02-18 22:07 UTC, y3l2n commented on viz/CustomHTMLCard/src/manifest.json
> +  "packageUrl": "https://datastudio.google.com/open/1QhuGDiHKUQ-yBs4nfAOesdhr9RBeQPvm",
The first page of the report should make it clearer what I'm looking at.

2020-02-18 22:07 UTC, y3l2n commented on viz/CustomHTMLCard/src/manifest.json
> +      "name": "CustomHTMLCard",
"HTML Card Template"

2020-02-18 22:07 UTC, y3l2n commented on viz/CustomHTMLCard/README.md
> +styling in the "Style" tab. User can mention the styling for the HTML body and row using the tags and class names. The classname for the row data is ".row". Sample styling looks like: https://datastu
use a reference link here.

2020-02-18 22:07 UTC, y3l2n commented on viz/CustomHTMLCard/README.md
> +Data Studio [community visualizations][community viz] allow you to write custom
Add a reference link for community viz

2020-02-18 22:39 UTC, praveena-pappu commented on viz/CustomHTMLCard/README.md
> +Data Studio [community visualizations][community viz] allow you to write custom
Updated as per review comments

2020-02-18 22:45 UTC, praveena-pappu commented on viz/CustomHTMLCard/src/manifest.json
> +  "packageUrl": "https://datastudio.google.com/open/1QhuGDiHKUQ-yBs4nfAOesdhr9RBeQPvm",
Updated

2020-02-18 22:46 UTC, praveena-pappu commented on viz/CustomHTMLCard/src/manifest.json
> +      "name": "CustomHTMLCard",
Updated the name

2020-02-27 18:56 UTC, musiciancodes approved these changes

2020-02-27 18:56 UTC, merged